### ISSUE TITLE
Mhook is crashing because it cannot find aws credentials

### ISSUE THREAD

**Issue by Tonnu** [wercker/mhook#17]
Running on devbox I get this stacktrace when running a build:

```
Jun 18 14:21:20 core-01 systemd[1]: Starting Pipeline Job...
Jun 18 14:21:50 core-01 mhook[2076]: panic: NoCredentialProviders: no valid providers in chain
Jun 18 14:21:50 core-01 mhook[2076]: goroutine 16 [running]:
Jun 18 14:21:50 core-01 mhook[2076]: runtime.panic(0x7ba520, 0xc208022ed0)
Jun 18 14:21:50 core-01 mhook[2076]: /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
Jun 18 14:21:50 core-01 mhook[2076]: main.targetSize(0xc208004480, 0x7ffd692b6df6, 0x14, 0xa)
Jun 18 14:21:50 core-01 mhook[2076]: /pipeline/build/mhook.go:98 +0x106
Jun 18 14:21:50 core-01 mhook[2076]: main.Fetch(0xc208004480, 0x7ffd692b6df6, 0x14, 0x0, 0x0, 0x0)
Jun 18 14:21:50 core-01 mhook[2076]: /pipeline/build/mhook.go:129 +0x24d
Jun 18 14:21:50 core-01 mhook[2076]: main.func·002(0xc20802a1c0)
Jun 18 14:21:50 core-01 mhook[2076]: /pipeline/build/mhook.go:235 +0x162
Jun 18 14:21:50 core-01 mhook[2076]: github.com/codegangsta/cli.(*App).Run(0xc208070200, 0xc20800e000, 0xb, 0xb, 0x0, 0x0)
Jun 18 14:21:50 core-01 mhook[2076]: /home/ubuntu/go/src/github.com/codegangsta/cli/app.go:165 +0xba9
Jun 18 14:21:50 core-01 mhook[2076]: main.main()
Jun 18 14:21:50 core-01 mhook[2076]: /pipeline/build/mhook.go:239 +0x16e
Jun 18 14:21:50 core-01 mhook[2076]: goroutine 19 [finalizer wait]:
Jun 18 14:21:50 core-01 mhook[2076]: runtime.park(0x415c20, 0xa21b30, 0xa1fda9)
Jun 18 14:21:50 core-01 mhook[2076]: /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
Jun 18 14:21:50 core-01 mhook[2076]: runtime.parkunlock(0xa21b30, 0xa1fda9)
Jun 18 14:21:50 core-01 mhook[2076]: /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
Jun 18 14:21:50 core-01 mhook[2076]: runfinq()
Jun 18 14:21:50 core-01 mhook[2076]: /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
Jun 18 14:21:50 core-01 mhook[2076]: runtime.goexit()
Jun 18 14:21:50 core-01 mhook[2076]: /usr/local/go/src/pkg/runtime/proc.c:1445
Jun 18 14:21:50 core-01 systemd[1]: sentcli-5582d3dc708e1b8839000023.service: control process exited, code=exited status=2
Jun 18 14:21:50 core-01 systemd[1]: Failed to start Pipeline Job.
Jun 18 14:21:50 core-01 systemd[1]: Unit sentcli-5582d3dc708e1b8839000023.service entered failed state.
Jun 18 14:21:50 core-01 systemd[1]: sentcli-5582d3dc708e1b8839000023.service failed.
Jun 18 14:21:55 core-01 systemd[1]: Stopped Pipeline Job.
```

**Comment by hatchan** [comment]
It looks like the go aws sdk library looks for the `HOME` directory, which doesn't look like it is set.

```
Jun 18 15:08:13 core-01 env[19677]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Jun 18 15:08:13 core-01 env[19677]: WERCKER_MAIN_PIPELINE_STARTED=1434640090
Jun 18 15:08:13 core-01 env[19677]: WERCKER_GIT_DOMAIN=github.com
Jun 18 15:08:13 core-01 env[19677]: WERCKER_GIT_OWNER=wercker
Jun 18 15:08:13 core-01 env[19677]: WERCKER_GIT_REPOSITORY=sentcli
Jun 18 15:08:13 core-01 env[19677]: WERCKER_GIT_BRANCH=
Jun 18 15:08:13 core-01 env[19677]: WERCKER_GIT_COMMIT=59cc141f8986b5338f39da783e08610c05a086b2
Jun 18 15:08:13 core-01 env[19677]: WERCKER_STARTED_BY=bvdberg
Jun 18 15:08:13 core-01 env[19677]: WERCKER_APPLICATION_ID=54c7aa204b64e1a011000098
Jun 18 15:08:13 core-01 env[19677]: WERCKER_APPLICATION_NAME=sentcli
Jun 18 15:08:13 core-01 env[19677]: WERCKER_APPLICATION_OWNER_NAME=wercker
```

**Comment by hatchan** [comment]
When adding the following environment variable, everything works: 

```
Environment=HOME=/home/core
```

**Comment by mwhooker** [comment]
Interesting that I didn't get this when I rebuilt stage yesterday. Looking for some errors in the logs, and will try to reproduce with devbox

**Comment by mwhooker** [comment]
oh I see, if mhook is run by fleet, it doesn't have the same environment as the core user

**Comment by mwhooker** [comment]
However, the kp units were able to authenticate and install kp successfully

**Comment by mwhooker** [comment]
confirmed that this isn't a problem in ec2, probably because it uses the IAM role provider

**Comment by mwhooker** [comment]
Oh here we go, the goamz stuff uses user.Current

https://github.com/AdRoll/goamz/blob/b0a456ecbd5367f922900045462906715ca794a5/aws/aws.go#L412-L417

and aws-sdk-go uses the env expansion. Will probably just write HOME=/home/core to /etc/environment or some other globally accessible env source

**Comment by mwhooker** [comment]
okay, I think the way I want to solve this is to wrap mhook on devbox in a wrapper script that exports HOME to the proper place
